# Generated by Django 2.2.2 on 2019-07-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
